apiVersion: apps/v1
kind: Deployment
metadata:
  name: speeddeploymentv2
spec:
  replicas: 2
  selector:
    matchLabels:
      name: speed
      version: "2.0"
  template:
    metadata:
      labels:
        name: speed
        version: "2.0"
      annotations:
        imageregistry: "https://hub.docker.com/"
        licence: Docker official licence
        warranty: 5 Years
    spec:
      containers:
        - name: speedcontainer
          image: raghravi94/speeddeployment:2.0
          ports:
            - name: tomcatport
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: "500m"  # Adjusted CPU request
              memory: "512Mi"
            limits:
              cpu: "1"  # Adjusted CPU limit
              memory: "512Mi"
